name: Test

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout hexium310/test
      uses: actions/checkout@v2
    - name: Test
      run: |
        echo $TEST
        echo ${{ secrets.TEST }}
        echo ${{ secrets.NAIYO }}
      env:
        TEST: ${{ secrets.TEST }}
